import { Whatsapp } from "venom-bot";

export const testClient: Whatsapp =  {
    "browser": {},
    "page": {
        "_isDragging": false
    },
    "session": "nome1",
    "options": {
        "folderNameToken": "tokens",
        "mkdirFolderToken": "",
        "headless": "new",
        "devtools": false,
        "debug": false,
        "logQR": true,
        "browserWS": "",
        "browserArgs": [
            "--no-zygote",
            "--log-level=3",
            "--disable-site-isolation-trials",
            "--no-experiments",
            "--ignore-gpu-blacklist",
            "--ignore-certificate-errors",
            "--ignore-certificate-errors-spki-list",
            "--disable-gpu",
            "--disable-extensions",
            "--disable-default-apps",
            "--enable-features=NetworkService",
            "--disable-setuid-sandbox",
            "--no-sandbox",
            "--disable-webgl",
            "--disable-infobars",
            "--window-position=0,0",
            "--ignore-certifcate-errors",
            "--ignore-certifcate-errors-spki-list",
            "--disable-threaded-animation",
            "--disable-threaded-scrolling",
            "--disable-in-process-stack-traces",
            "--disable-histogram-customizer",
            "--disable-gl-extensions",
            "--disable-composited-antialiasing",
            "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
            "--disable-background-networking",
            "--enable-features=NetworkService,NetworkServiceInProcess",
            "--disable-background-timer-throttling",
            "--disable-backgrounding-occluded-windows",
            "--disable-breakpad",
            "--disable-client-side-phishing-detection",
            "--disable-component-extensions-with-background-pages",
            "--disable-dev-shm-usage",
            "--disable-features=Translate",
            "--disable-hang-monitor",
            "--disable-ipc-flooding-protection",
            "--disable-popup-blocking",
            "--disable-prompt-on-repost",
            "--disable-renderer-backgrounding",
            "--disable-sync",
            "--force-color-profile=srgb",
            "--metrics-recording-only",
            "--no-first-run",
            "--enable-automation",
            "--password-store=basic",
            "--use-mock-keychain",
            "--enable-blink-features=IdleDetection",
            "--export-tagged-pdf",
            "about:blank",
            "--user-data-dir=C:\\Users\\HASTJW\\Desktop\\wpp_poc\\tokens\\nome1"
        ],
        "addBrowserArgs": [],
        "puppeteerOptions": {
            "userDataDir": "C:\\Users\\HASTJW\\Desktop\\wpp_poc\\tokens\\nome1",
            "ignoreHTTPSErrors": true
        },
        "disableSpins": true,
        "disableWelcome": true,
        "updatesLog": false,
        "autoClose": 30000,
        "createPathFileToken": true,
        "waitForLogin": true,
        "BrowserFetcher": true,
        "forceConnect": true,
        "attemptsForceConnectLoad": 5,
        "forceConnectTime": 1000,
        "addProxy": [],
        "browserPathExecutable": null,
        "session": "nome1"
    },
    "spinnies": {
        "options": {
            "spinnerColor": "greenBright",
            "succeedColor": "green",
            "failColor": "red",
            "spinner": {
                "interval": 50,
                "frames": [
                    "⠋",
                    "⠙",
                    "⠹",
                    "⠸",
                    "⠼",
                    "⠴",
                    "⠦",
                    "⠧",
                    "⠇",
                    "⠏"
                ]
            },
            "disableSpins": true,
            "succeedPrefix": "✓",
            "failPrefix": "✖"
        },
        "spinners": {
            "donate-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "fail",
                "text": "Help Keep This Project Going! Know more: https://github.com/orkestral/venom/blob/master/docs/getting-started/donate.md"
            },
            "node-version-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "succeed",
                "text": "Node.js version verified successfully!"
            },
            "browser-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "succeed",
                "text": "headless option is active, browser hidden"
            },
            "executable-path-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "succeed",
                "text": "Executable path browser: C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"
            },
            "browser-Platform-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "succeed",
                "text": "Platform: win32"
            },
            "browser-Version-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "succeed",
                "text": "Browser Version: Chrome/117.0.5938.134"
            },
            "whatzapp-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "succeed",
                "text": "Page successfully accessed"
            },
            "whatzapp-intro-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "succeed",
                "text": "Successfully connected!"
            },
            "session-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "succeed",
                "text": "[instance: nome1]: Connected"
            },
            "whatzapp-mode-main-nome1": {
                "succeedColor": "green",
                "failColor": "red",
                "spinnerColor": "greenBright",
                "succeedPrefix": "✓",
                "failPrefix": "✖",
                "status": "succeed",
                "text": "Successfully main page!"
            }
        },
        "isCursorHidden": false,
        "currentInterval": null,
        "stream": {
            "connecting": false,
            "_hadError": false,
            "_parent": null,
            "_host": null,
            "_closeAfterHandlingError": false,
            "_readableState": {
                "objectMode": false,
                "highWaterMark": 0,
                "buffer": {
                    "head": null,
                    "tail": null,
                    "length": 0
                },
                "length": 0,
                "pipes": [],
                "flowing": null,
                "ended": false,
                "endEmitted": false,
                "reading": false,
                "constructed": true,
                "sync": true,
                "needReadable": false,
                "emittedReadable": false,
                "readableListening": false,
                "resumeScheduled": false,
                "errorEmitted": false,
                "emitClose": false,
                "autoDestroy": true,
                "destroyed": false,
                "errored": null,
                "closed": false,
                "closeEmitted": false,
                "defaultEncoding": "utf8",
                "awaitDrainWriters": null,
                "multiAwaitDrain": false,
                "readingMore": false,
                "dataEmitted": false,
                "decoder": null,
                "encoding": null
            },
            "_events": {},
            "_eventsCount": 1,
            "_writableState": {
                "objectMode": false,
                "highWaterMark": 16384,
                "finalCalled": false,
                "needDrain": false,
                "ending": false,
                "ended": false,
                "finished": false,
                "destroyed": false,
                "decodeStrings": false,
                "defaultEncoding": "utf8",
                "length": 0,
                "writing": false,
                "corked": 0,
                "sync": false,
                "bufferProcessing": false,
                "writecb": null,
                "writelen": 0,
                "afterWriteTickInfo": null,
                "buffered": [],
                "bufferedIndex": 0,
                "allBuffers": true,
                "allNoop": true,
                "pendingcb": 0,
                "constructed": true,
                "prefinished": false,
                "errorEmitted": false,
                "emitClose": false,
                "autoDestroy": true,
                "errored": null,
                "closed": false,
                "closeEmitted": false
            },
            "allowHalfOpen": false,
            "_sockname": null,
            "_pendingData": null,
            "_pendingEncoding": "",
            "server": null,
            "_server": null,
            "columns": 198,
            "rows": 11,
            "_type": "tty",
            "fd": 2,
            "_isStdio": true
        },
        "lineCount": 0,
        "currentFrameIndex": 0,
        "spin": false
    },
    "spinStatus": {
        "apiInject": "",
        "autoCloseRemain": 0,
        "previousText": "Connected",
        "previousStatus": "succeed",
        "state": ""
    },
    "autoCloseInterval": null,
    "listenerEmitter": {
        "_events": {
            "onStateChange": [
                null,
                null
            ]
        },
        "_eventsCount": 3
    }
}